FROM postgres:13.3
 

COPY ./*.txt /dbExtensionBuild/

RUN apt-get update 
RUN apt-get -y install python3 postgresql-plpython3-13 python3-pip

RUN pip3 install -r /dbExtensionBuild/plpython_requirements.txt

RUN  apt-get clean && \
     rm -rf /var/cache/apt/* /var/lib/apt/lists/*
